# Generated by Django 5.0 on 2025-10-25 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoTrafico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(choices=[('accidente', 'Accidente'), ('congestion', 'Congestión'), ('obras', 'Obras en la vía'), ('incidente', 'Incidente'), ('clima', 'Condiciones climáticas')], help_text='Tipo de evento de tráfico', max_length=20)),
                ('descripcion', models.TextField(help_text='Descripción detallada del evento')),
                ('ubicacion', models.CharField(help_text='Ubicación del evento', max_length=255)),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, help_text='Coordenada de latitud', max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, help_text='Coordenada de longitud', max_digits=11, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('resuelto', 'Resuelto'), ('en_proceso', 'En Proceso')], default='activo', help_text='Estado actual del evento', max_length=15)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación del evento')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
                ('fecha_resolucion', models.DateTimeField(blank=True, help_text='Fecha y hora de resolución del evento', null=True)),
                ('prioridad', models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta'), (4, 'Crítica')], default=1, help_text='Nivel de prioridad del evento')),
                ('reportado_por', models.CharField(blank=True, help_text='Usuario o sistema que reportó el evento', max_length=100)),
            ],
            options={
                'verbose_name': 'Evento de Tráfico',
                'verbose_name_plural': 'Eventos de Tráfico',
                'db_table': 'eventos_trafico',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['tipo_evento'], name='eventos_tra_tipo_ev_4af408_idx'), models.Index(fields=['estado'], name='eventos_tra_estado_3076a6_idx'), models.Index(fields=['fecha_creacion'], name='eventos_tra_fecha_c_bfcb1d_idx'), models.Index(fields=['ubicacion'], name='eventos_tra_ubicaci_19d1c4_idx')],
            },
        ),
    ]
