# Generated by Django 5.0 on 2025-10-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservicios_eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventotrafico',
            name='actualizado_por_id_externo',
            field=models.IntegerField(blank=True, help_text='ID del usuario que actualizó el evento (referencia externa)', null=True),
        ),
        migrations.AlterField(
            model_name='eventotrafico',
            name='creado_por_id_externo',
            field=models.IntegerField(blank=True, help_text='ID del usuario que creó el evento (referencia externa)', null=True),
        ),
    ]
