# Generated by Django 5.0 on 2025-10-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservicios_eventos', '0002_change_user_id_to_integer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorutaafectada',
            name='ruta_id_externo',
            field=models.IntegerField(help_text='ID de la ruta en el sistema externo'),
        ),
        migrations.AlterField(
            model_name='eventotrafico',
            name='conductor_id_externo',
            field=models.IntegerField(blank=True, help_text='ID del conductor en MS Transporte', null=True),
        ),
        migrations.AlterField(
            model_name='eventotrafico',
            name='vehiculo_id_externo',
            field=models.IntegerField(blank=True, help_text='ID del vehículo en MS Transporte', null=True),
        ),
        migrations.AlterField(
            model_name='eventotrafico',
            name='viaje_id_externo',
            field=models.IntegerField(blank=True, help_text='ID del viaje en MS Transporte', null=True),
        ),
    ]
