# Generated by Django 5.0 on 2025-10-26 14:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservicios_eventos', '0003_alter_eventorutaafectada_ruta_id_externo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventotrafico',
            name='area_afectacion',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='Área geográfica afectada por el evento (polígono o círculo)', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='eventotrafico',
            name='ubicacion',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Ubicación geográfica del evento (latitud, longitud)', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='eventotrafico',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitud del evento (legacy - usar ubicacion)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='eventotrafico',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitud del evento (legacy - usar ubicacion)', max_digits=9, null=True),
        ),
        migrations.AddIndex(
            model_name='eventotrafico',
            index=models.Index(fields=['ubicacion'], name='evento_traf_ubicaci_7c2435_idx'),
        ),
        migrations.AddIndex(
            model_name='eventotrafico',
            index=models.Index(fields=['area_afectacion'], name='evento_traf_area_af_836cc5_idx'),
        ),
    ]
