# Generated by Django 5.0 on 2025-10-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservicios_eventos', '0004_eventotrafico_area_afectacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventotrafico',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=9, help_text='Latitud del evento (legacy - usar ubicacion)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='eventotrafico',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=9, help_text='Longitud del evento (legacy - usar ubicacion)', max_digits=12, null=True),
        ),
    ]
